#version: '3.9'

services:
  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=neuralshoes
    ports:
      - "5432:5432"

  # Servicio para el backend Django
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-key-for-development
      - DB_NAME=neuralshoes
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8001:8000"  # 8001 en el host

volumes:
  postgres_data: