"""
Django settings for NeuralShoes project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ry6%bb+u2cvfl=v(=c86#d361dg_4%v2s0b2!#r3x2g69(3=)9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'django_keycloak_auth',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <-- Agrega esto al inicio
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


CORS_ALLOW_ALL_ORIGINS = True

# Configuración de Keycloak
KEYCLOAK_SERVER_URL = 'http://keycloak:8080/' #'http://localhost:8080/'  # Usa el nombre del servicio interno (si usas Docker)
KEYCLOAK_REALM = 'neuralshoes'
KEYCLOAK_CLIENT_ID = 'django_api'
KEYCLOAK_CLIENT_SECRET = 'P6irtejuCA3whyD1CC9s9jVDi6nA4fXI'  # El que copiaste de la pestaña Credentials

# Opcional: para acceso público a tu API desde fuera de Docker
KEYCLOAK_PUBLIC_SERVER_URL = 'http://localhost:8080/'  # URL para clientes externos

KEYCLOAK_CONFIG = {
    'SERVER_URL': 'http://keycloak:8080/',
    'REALM': 'neuralshoes',
    'CLIENT_ID': 'django_api',
    'CLIENT_SECRET': 'P6irtejuCA3whyD1CC9s9jVDi6nA4fXI',  # El que copiaste de la pestaña Credentials
    'KEYCLOAK_PUBLIC_KEY':'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA27gP4fHxTKVw6xbIdJygjDZmo9Whtk6YkTYXdz/mtDq9ecKpKSa8jym/ruOVKHOVT6+pm2WSDGQzPyrf8zE8LoFzMHTzy4xUGp7IluZKRBqzmYneqiYfBZrqRsrP6+wOnhDxOn8TAIUdQ7hbUIrPm9HCoNEv1UDIr6CrQ+MK3jg2o5vb6gVM6yNDmnkl3YKrg9vByNeACTFPDYBL1nAUwW1fFntjOkVjMIIMCsmk6ZZLBqdIvH+x+F5XosBXFGHfzzdjC/FzyEpOwVDMo3jiAILflATYIb7jWha25elnxY3+UaZs5IBrxl1rCy+c69IMjEn6VNH53JfEqxfPqypF3wIDAQAB',
    # 'PUBLIC_SERVER_URL': KEYCLOAK_PUBLIC_SERVER_URL,    
    # 'PUBLIC_REALM': KEYCLOAK_PUBLIC_SERVER_URL,
    
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.KeycloakAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', 
]


ROOT_URLCONF = 'NeuralShoes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NeuralShoes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'neuralshoes'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'

LANGUAGE_CODE = 'es'

#TIME_ZONE = 'UTC'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
