# Generated by Django 5.2 on 2025-05-11 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='talla_producto',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='talla_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tallaproducto'),
            preserve_default=False,
        ),
    ]
