# Generated by Django 5.2 on 2025-05-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_color_producto_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
