# Generated by Django 5.2 on 2025-05-14 00:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_producto_color_delete_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='talla_producto',
        ),
        migrations.CreateModel(
            name='ProductoTallaColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talla')),
            ],
            options={
                'unique_together': {('producto', 'talla', 'color')},
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='variacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.productotallacolor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(through='api.ProductoTallaColor', to='api.color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.ManyToManyField(through='api.ProductoTallaColor', to='api.talla'),
        ),
        migrations.DeleteModel(
            name='TallaProducto',
        ),
    ]
