# Generated by Django 5.2.1 on 2025-05-19 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='fecha_creacion',
            new_name='creado',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='activo',
        ),
        migrations.AddField(
            model_name='carrito',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='api.cliente'),
        ),
    ]
