# Generated by Django 5.2.1 on 2025-05-19 01:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_fecha_creacion_carrito_creado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='products/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.producto')),
            ],
        ),
    ]
