# Generated by Django 5.2.1 on 2025-05-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_producto_imagen_productoimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoimagen',
            name='descripcion',
        ),
    ]
