# Generated by Django 5.2.1 on 2025-05-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_productoimagen_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/brands'),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(upload_to='media/products'),
        ),
    ]
